"""Supplemental flat clothing tags for the character prompt builder.

The tuples in this module deliberately contain only data.  Keeping them
independent from ``prompt_tag_builder_service`` avoids a circular import while
allowing that service to construct its own ``TagOption`` instances.
"""

from typing import Final

type ClothingTagDefinition = tuple[str, str, str]


OUTFIT_ARCHETYPE_SAFE: Final[tuple[ClothingTagDefinition, ...]] = (
    ("t_shirt", "T恤", "t-shirt"),
    ("shirt", "襯衫", "shirt"),
    ("blouse", "女式襯衫", "blouse"),
    ("tank_top", "背心", "tank top"),
    ("camisole", "細肩帶背心", "camisole"),
    ("tube_top", "平口上衣", "tube top"),
    ("halter_top", "掛脖上衣", "halter top"),
    ("crop_top", "短版上衣", "crop top"),
    ("polo_shirt", "Polo 衫", "polo shirt"),
    ("jersey", "球衣", "jersey"),
    ("sweater", "毛衣", "sweater"),
    ("hoodie", "帽T", "hoodie"),
    ("sweatshirt", "大學T", "sweatshirt"),
    ("cardigan", "開襟衫", "cardigan"),
    ("vest", "西裝背心／馬甲", "waistcoat"),
    ("turtleneck_top", "高領上衣", "turtleneck top"),
    ("trousers", "長褲", "trousers"),
    ("jeans", "牛仔褲", "jeans"),
    ("shorts", "短褲", "shorts"),
    ("hot_pants", "超短褲", "hot pants"),
    ("cargo_pants", "工裝褲", "cargo pants"),
    ("joggers", "束口褲", "joggers"),
    ("sweatpants", "休閒運動褲", "sweatpants"),
    ("leggings", "緊身褲", "leggings"),
    ("yoga_pants", "瑜珈褲", "yoga pants"),
    ("cycling_shorts", "單車褲", "cycling shorts"),
    ("culottes", "寬褲／裙褲", "culottes"),
    ("skirt", "裙子", "skirt"),
    ("pleated_skirt", "百褶裙", "pleated skirt"),
    ("a_line_skirt", "A字裙", "a-line skirt"),
    ("pencil_skirt", "鉛筆裙", "pencil skirt"),
    ("circle_skirt", "圓裙", "circle skirt"),
    ("wrap_skirt", "裹裙", "wrap skirt"),
    ("denim_skirt", "牛仔裙", "denim skirt"),
    ("tennis_skirt", "網球裙", "tennis skirt"),
    ("dress", "洋裝", "dress"),
    ("sundress", "夏季洋裝", "sundress"),
    ("evening_gown", "晚禮服", "evening gown"),
    ("slip_dress", "細肩帶洋裝", "slip dress"),
    ("bodycon_dress", "貼身洋裝", "bodycon dress"),
    ("shirt_dress", "襯衫洋裝", "shirt dress"),
    ("sweater_dress", "毛衣洋裝", "sweater dress"),
    ("jumpsuit", "連身長褲", "jumpsuit"),
    ("romper", "連身短褲", "romper"),
    ("overalls", "吊帶褲", "overalls"),
    ("bodysuit", "連體衣", "bodysuit"),
    ("jacket", "夾克", "jacket"),
    ("coat", "大衣", "coat"),
    ("blazer", "西裝外套", "blazer"),
    ("parka", "派克大衣", "parka"),
    ("puffer_jacket", "羽絨外套", "puffer jacket"),
    ("denim_jacket", "牛仔外套", "denim jacket"),
    ("leather_jacket", "皮衣", "leather jacket"),
    ("bomber_jacket", "飛行外套", "bomber jacket"),
    ("windbreaker", "防風外套", "windbreaker jacket"),
    ("cloak", "斗篷", "cloak"),
    ("raincoat", "雨衣", "raincoat"),
    ("bra", "胸罩", "bra"),
    ("bralette", "Bralette 無鋼圈內衣", "bralette"),
    ("sports_bra", "運動內衣", "sports bra"),
    ("strapless_bra", "無肩帶內衣", "strapless bra"),
    ("bandeau_bra", "平口內衣", "bandeau bra"),
    ("push_up_bra", "集中型內衣", "push-up bra"),
    ("balconette_bra", "半罩杯內衣", "balconette bra"),
    ("triangle_bra", "三角罩杯", "triangle bra"),
    ("panties", "女式內褲", "panties"),
    ("briefs", "三角內褲", "briefs"),
    ("bikini_briefs", "比基尼型內褲", "bikini briefs"),
    ("hipster_briefs", "低腰平口內褲", "hipster panties"),
    ("boyshorts", "女式平口褲", "boyshorts"),
    ("high_waisted_briefs", "高腰內褲", "high-waisted panties"),
    ("seamless_underwear", "無痕內褲", "seamless panties"),
    ("thong", "丁字褲", "thong"),
    ("g_string", "G-string 細帶內褲", "g-string"),
    ("tanga", "Tanga 內褲", "tanga panties"),
    ("cheeky_panties", "半包臀內褲", "cheeky panties"),
    ("lace_panties", "蕾絲內褲", "lace panties"),
    ("side_tie_panties", "側綁帶內褲", "side-tie panties"),
    ("high_cut_panties", "高衩內褲", "high-cut panties"),
    ("pajamas", "睡衣", "pajamas"),
    ("pajama_top", "睡衣上衣", "pajama top"),
    ("pajama_pants", "睡褲", "pajama pants"),
    ("pajama_shorts", "睡衣短褲", "pajama shorts"),
    ("nightgown", "睡裙", "nightgown"),
    ("nightshirt", "睡衣襯衫", "nightshirt"),
    ("robe", "睡袍", "robe"),
    ("bathrobe", "浴袍", "bathrobe"),
    ("loungewear", "居家服", "loungewear"),
    ("onesie", "連身睡衣", "onesie"),
    ("dress_shirt", "正裝襯衫", "dress shirt"),
    ("dress_pants", "西裝褲", "dress pants"),
    ("chinos", "卡其褲", "chinos"),
    ("suit_jacket", "西裝上衣", "suit jacket"),
    ("undershirt", "汗衫", "undershirt"),
    ("boxers", "四角寬鬆內褲", "boxers"),
    ("boxer_briefs", "貼身四角褲", "boxer briefs"),
    ("trunks", "短版四角褲", "trunks"),
    ("jockstrap", "運動護襠內褲", "jockstrap"),
    ("sports_shirt", "運動上衣", "sports shirt"),
    ("sports_shorts", "運動短褲", "sports shorts"),
    ("compression_shirt", "壓縮衣", "compression shirt"),
    ("compression_tights", "壓縮褲", "compression tights"),
    ("track_pants", "運動套裝長褲", "track pants"),
    ("tracksuit", "運動套裝", "tracksuit"),
    ("swim_briefs", "三角泳褲", "swim briefs"),
    ("swim_trunks", "泳褲", "swim trunks"),
    ("board_shorts", "衝浪褲", "board shorts"),
    ("jammer", "五分競泳褲", "swim jammer"),
    ("rash_guard", "防磨／防曬泳衣", "rash guard"),
    ("bikini", "比基尼", "bikini"),
    ("one_piece_swimsuit", "一件式泳裝", "one-piece swimsuit"),
    ("tankini", "Tankini 兩件式泳裝", "tankini"),
    ("monokini", "Monokini 挖空連身泳裝", "monokini"),
    ("swim_dress", "泳裙", "swim dress"),
    ("competitive_swimsuit", "競泳泳裝", "competitive swimsuit"),
    ("school_swimsuit", "學校泳裝（死庫水）", "school swimsuit"),
    ("cutout_swimsuit", "挖空泳裝", "cutout swimsuit"),
    ("high_leg_swimsuit", "高衩泳裝", "high-leg swimsuit"),
    ("frilled_bikini", "荷葉邊比基尼", "frilled bikini"),
    ("ruched_bikini", "抓皺比基尼", "ruched bikini"),
    ("triangle_bikini", "三角比基尼", "triangle bikini"),
    ("halter_bikini", "掛脖比基尼", "halter bikini"),
    ("bandeau_bikini", "平口比基尼", "bandeau bikini"),
    ("string_bikini", "綁帶比基尼", "string bikini"),
    ("high_waisted_bikini", "高腰比基尼", "high-waisted bikini"),
    ("sports_bikini", "運動比基尼", "sports bikini"),
    ("underwire_bikini", "鋼圈比基尼", "underwire bikini"),
    ("side_tie_bikini", "側綁帶比基尼", "side-tie bikini"),
    ("skirted_bikini", "裙式比基尼", "skirted bikini"),
    ("high_cut_one_piece", "高衩一件式泳裝", "high-cut one-piece swimsuit"),
    ("backless_swimsuit", "露背泳裝", "backless swimsuit"),
    ("zip_front_swimsuit", "前拉鍊泳裝", "zip-front swimsuit"),
    ("racing_one_piece", "競速型一件式泳裝", "racing one-piece swimsuit"),
    ("utility_jumpsuit", "工裝連身服", "utility jumpsuit"),
    ("poncho", "斗篷式披肩", "poncho"),
    ("wrap_dress", "裹身洋裝", "wrap dress"),
)


OUTFIT_ARCHETYPE_ADULT: Final[tuple[ClothingTagDefinition, ...]] = (
    ("micro_bikini", "極小比基尼（18+）", "micro bikini"),
    ("slingshot_swimsuit", "吊帶式泳裝（18+）", "slingshot swimsuit"),
    ("lingerie_set", "情趣內衣套裝（18+）", "lingerie set"),
    ("babydoll", "Babydoll 睡衣（18+）", "babydoll lingerie"),
    ("lingerie_chemise", "Chemise 情趣睡衣（18+）", "lingerie chemise"),
    ("teddy_lingerie", "Teddy 連身內衣（18+）", "teddy lingerie"),
    ("corset", "馬甲（18+）", "corset"),
    ("bustier", "Bustier 馬甲上衣（18+）", "bustier"),
    ("basque", "Basque 馬甲式內衣（18+）", "basque lingerie"),
    ("bodystocking", "連身襪衣／全身貼身襪衣（18+）", "bodystocking"),
    ("sheer_bodysuit", "透膚連身衣（18+）", "sheer bodysuit"),
    ("lace_bodysuit", "蕾絲連身衣（18+）", "lace bodysuit"),
    ("mesh_bodysuit", "網紗連身衣（18+）", "mesh bodysuit"),
    ("garter_lingerie_set", "吊襪帶套組（18+）", "garter lingerie set"),
    ("cupless_bra", "開杯內衣（18+）", "cupless bra"),
    ("front_closure_bra", "前開式內衣（18+）", "front-closure bra"),
    ("high_cut_bodysuit", "高衩連身衣（18+）", "high-cut bodysuit"),
    ("strappy_panties", "綁帶內褲（18+）", "strappy panties"),
    ("lace_thong", "蕾絲丁字褲（18+）", "lace thong"),
    ("mesh_panties", "網紗內褲（18+）", "mesh panties"),
    ("sheer_panties", "透膚內褲（18+）", "sheer panties"),
    ("crotchless_panties", "開襠內褲（18+）", "crotchless panties"),
    ("open_back_panties", "露臀內褲（18+）", "open-back panties"),
    ("cutout_panties", "挖空內褲（18+）", "cutout panties"),
    ("side_tie_thong", "側綁帶丁字褲（18+）", "side-tie thong"),
    ("sheer_robe", "透紗睡袍（18+）", "sheer robe"),
    ("lace_robe", "蕾絲睡袍（18+）", "lace robe"),
    ("silk_robe", "絲質睡袍（18+）", "silk robe"),
    ("satin_nightgown", "緞面睡裙（18+）", "satin nightgown"),
    ("lace_nightgown", "蕾絲睡裙（18+）", "lace nightgown"),
    ("slip_nightdress", "細肩帶睡裙（18+）", "slip nightdress"),
    ("see_through_nightwear", "透視睡衣（18+）", "see-through nightwear"),
    ("extreme_micro_bikini", "極限微型比基尼（18+）", "extreme micro bikini"),
    (
        "string_one_piece_swimsuit",
        "細帶泳裝（18+）",
        "string one-piece swimsuit",
    ),
    ("adult_lace_cage_dress", "蕾絲籠狀情趣裙（18+）", "lace cage lingerie dress"),
    (
        "adult_strappy_cage_bodysuit",
        "多帶籠狀連身衣（18+）",
        "strappy cage bodysuit",
    ),
    (
        "adult_underbust_corset_set",
        "下胸馬甲內衣套組（18+）",
        "underbust corset lingerie set",
    ),
    ("adult_open_cup_teddy", "開杯連身內衣（18+）", "open-cup teddy lingerie"),
    (
        "adult_fishnet_mini_dress",
        "漁網迷你情趣裙（18+）",
        "fishnet mini lingerie dress",
    ),
    (
        "adult_suspender_bodysuit",
        "吊襪帶連身內衣（18+）",
        "lingerie bodysuit with attached garters",
    ),
    (
        "adult_pearl_string_lingerie",
        "珍珠細帶內衣（18+）",
        "pearl-strand lingerie",
    ),
    ("adult_keyhole_bodysuit", "鑰匙孔挖空連身衣（18+）", "keyhole bodysuit"),
    ("adult_backless_teddy", "露背連身內衣（18+）", "backless teddy lingerie"),
    ("adult_open_side_bodysuit", "側開連身衣（18+）", "open-side bodysuit"),
    (
        "adult_strappy_garter_dress",
        "綁帶吊襪情趣裙（18+）",
        "strappy garter lingerie dress",
    ),
    ("adult_chainmail_bikini", "鍊甲比基尼（18+）", "chainmail bikini"),
    (
        "adult_sheer_halter_teddy",
        "透膚掛脖連身內衣（18+）",
        "sheer halter teddy lingerie",
    ),
    (
        "adult_open_back_lingerie_set",
        "露背情趣內衣套組（18+）",
        "open-back lingerie set",
    ),
)


ACCESSORIES_SAFE: Final[tuple[ClothingTagDefinition, ...]] = (
    ("baseball_cap", "棒球帽", "baseball cap"),
    ("hat", "帽子", "hat"),
    ("beret", "貝雷帽", "beret"),
    ("beanie", "毛帽", "beanie"),
    ("sun_hat", "遮陽帽", "sun hat"),
    ("hair_ribbon", "髮飾緞帶", "hair ribbon"),
    ("hair_clip", "髮夾", "hair clip"),
    ("hair_claw", "抓夾", "hair claw clip"),
    ("scrunchie", "髮圈", "scrunchie"),
    ("headband", "髮箍", "headband"),
    ("bandana", "方巾／頭巾", "bandana"),
    ("tie", "領帶", "necktie"),
    ("bow_tie", "蝴蝶領結", "bow tie"),
    ("bracelet", "手鍊", "bracelet"),
    ("anklet", "腳鍊", "anklet"),
    ("fingerless_gloves", "無指手套", "fingerless gloves"),
    ("mittens", "連指手套", "mittens"),
    ("wristband", "運動護腕", "athletic wristband"),
    ("watch", "手錶", "wristwatch"),
    ("belt", "腰帶", "belt"),
    ("waist_chain", "腰鍊", "waist chain"),
    ("suspenders", "吊褲帶", "suspenders"),
    ("backpack", "後背包", "backpack"),
    ("handbag", "手提包", "handbag"),
    ("shoulder_bag", "肩背包", "shoulder bag"),
    ("crossbody_bag", "斜背包", "crossbody bag"),
    ("clutch", "手拿包", "clutch bag"),
    ("coin_purse", "零錢包", "coin purse"),
    ("socks", "一般襪子", "socks"),
    ("stockings", "長絲襪／長襪", "stockings"),
    ("garter_stockings", "吊帶絲襪", "garter stockings"),
    ("pantyhose", "薄型褲襪", "pantyhose"),
    ("tights", "厚型褲襪", "tights"),
    ("leg_warmers", "腿套", "leg warmers"),
    ("bucket_hat", "漁夫帽", "bucket hat"),
    ("newsboy_cap", "報童帽", "newsboy cap"),
    ("fascinator", "小禮帽頭飾", "fascinator headpiece"),
    ("lapel_pin", "領針", "decorative lapel pin"),
    ("cufflinks", "袖扣", "ornate cufflinks"),
    ("pocket_square", "口袋巾", "folded pocket square"),
)


ACCESSORIES_ADULT: Final[tuple[ClothingTagDefinition, ...]] = (
    ("adult_accessory_garter_belt", "吊襪帶（18+）", "garter belt"),
    ("adult_accessory_sheer_coverup", "透紗罩衫（18+）", "sheer cover-up"),
    ("adult_accessory_sarong", "沙龍裙／罩裙（18+）", "sarong"),
    (
        "adult_accessory_lace_top_stockings",
        "蕾絲邊絲襪（18+）",
        "lace-top stockings",
    ),
    (
        "adult_accessory_fishnet_stockings",
        "漁網絲襪（18+）",
        "fishnet stockings",
    ),
    (
        "adult_accessory_fishnet_pantyhose",
        "漁網褲襪（18+）",
        "fishnet pantyhose",
    ),
    ("adult_accessory_seamed_stockings", "後線絲襪（18+）", "seamed stockings"),
    (
        "adult_accessory_suspender_tights",
        "吊帶造型褲襪（18+）",
        "suspender tights",
    ),
    ("adult_accessory_thigh_garter", "大腿環／腿環（18+）", "thigh garter"),
    ("adult_accessory_leg_harness", "腿部束帶（18+）", "leg harness"),
    ("adult_accessory_collar", "項圈（18+）", "decorative neck collar"),
    ("adult_accessory_leather_collar", "皮質項圈（18+）", "leather collar"),
    ("adult_accessory_lace_choker", "蕾絲頸圈（18+）", "lace choker"),
    ("adult_accessory_nipple_pasties", "胸貼（18+）", "nipple pasties"),
    ("adult_accessory_arm_cuffs", "手臂環（18+）", "arm cuffs"),
    ("adult_accessory_lace_mask", "蕾絲面罩（18+）", "lace masquerade mask"),
    ("adult_accessory_opera_gloves", "長手套（18+）", "opera gloves"),
    (
        "adult_accessory_detachable_collar",
        "可拆式項圈（18+）",
        "detachable intimate collar",
    ),
    (
        "adult_accessory_thigh_cuffs",
        "情趣大腿環銬（18+）",
        "decorative intimate thigh cuffs",
    ),
    (
        "adult_accessory_lace_wristlets",
        "蕾絲腕飾（18+）",
        "delicate lace wristlets",
    ),
    (
        "adult_accessory_satin_blindfold",
        "緞面眼罩（18+）",
        "decorative satin blindfold",
    ),
    (
        "adult_accessory_hip_chain",
        "臀胯鍊飾（18+）",
        "draped hip-chain jewelry",
    ),
    (
        "adult_accessory_body_garters",
        "身體吊帶環（18+）",
        "decorative body garter harness",
    ),
    (
        "adult_accessory_pearl_body_strands",
        "珍珠身體鍊（18+）",
        "draped pearl body chain",
    ),
    (
        "adult_accessory_feather_eye_mask",
        "羽飾情趣眼罩（18+）",
        "decorative feathered eye mask",
    ),
    (
        "adult_accessory_chain_pasties",
        "鍊式胸貼（18+）",
        "ornamental chain-linked nipple pasties",
    ),
    (
        "adult_accessory_lace_anklets",
        "蕾絲腳踝飾（18+）",
        "delicate lace ankle adornments",
    ),
    (
        "adult_accessory_strappy_armbands",
        "多帶手臂環（18+）",
        "strappy upper-arm bands",
    ),
    (
        "adult_accessory_crystal_body_gems",
        "水晶人體藝術貼飾（18+）",
        "ornamental crystal body gems",
    ),
    (
        "adult_accessory_satin_thigh_bows",
        "緞帶大腿蝴蝶結（18+）",
        "decorative satin thigh bows",
    ),
    (
        "adult_accessory_navel_chain",
        "珠寶肚臍穿孔鍊（18+）",
        "jeweled navel-piercing chain",
    ),
    (
        "adult_accessory_sheer_elbow_gloves",
        "透膚肘長手套（18+）",
        "sheer elbow-length gloves",
    ),
)


OUTFIT_MATERIALS_SAFE: Final[tuple[ClothingTagDefinition, ...]] = (
    ("faux_leather", "人造皮革", "faux-leather fabric"),
    ("knit", "針織", "knitted fabric"),
    ("nylon", "尼龍", "nylon fabric"),
    ("chiffon", "雪紡", "chiffon fabric"),
    ("fishnet", "漁網", "fishnet fabric"),
    ("sheer", "透膚", "sheer fabric"),
    ("patent_leather", "漆皮", "patent leather"),
    ("satin", "緞面", "satin fabric"),
    ("organza", "歐根紗", "organza fabric"),
    ("tulle", "薄紗網", "tulle fabric"),
    ("jersey_knit", "針織汗布", "jersey-knit fabric"),
    ("ribbed_knit", "羅紋針織", "ribbed knit fabric"),
    ("canvas", "帆布", "canvas fabric"),
    ("tweed", "花呢", "tweed fabric"),
    ("corduroy", "燈芯絨", "corduroy fabric"),
    ("fleece", "刷毛", "fleece fabric"),
    ("faux_fur", "人造毛皮", "faux-fur fabric"),
    ("sequined", "亮片布", "sequined fabric"),
    ("metallic_textile", "金屬光澤布", "metallic textile"),
    ("vinyl", "亮面 Vinyl／PVC 材質", "glossy vinyl fabric"),
    ("neoprene", "氯丁橡膠", "neoprene fabric"),
    ("bamboo_fiber", "竹纖維", "bamboo-fiber fabric"),
    ("ramie", "苧麻", "ramie fabric"),
    ("cashmere", "喀什米爾", "cashmere fabric"),
)


OUTFIT_MATERIALS_ADULT: Final[tuple[ClothingTagDefinition, ...]] = ()


OUTFIT_PALETTE_SAFE: Final[tuple[ClothingTagDefinition, ...]] = (
    ("palette_black", "黑色", "black clothing palette"),
    ("palette_white", "白色", "white clothing palette"),
    ("palette_gray", "灰色", "gray clothing palette"),
    ("palette_silver", "銀色", "silver clothing palette"),
    ("palette_red", "紅色", "red clothing palette"),
    ("palette_burgundy", "酒紅色", "burgundy clothing palette"),
    ("palette_pink", "粉紅色", "pink clothing palette"),
    ("palette_orange", "橙色", "orange clothing palette"),
    ("palette_yellow", "黃色", "yellow clothing palette"),
    ("palette_gold", "金色", "gold clothing palette"),
    ("palette_green", "綠色", "green clothing palette"),
    ("palette_olive", "橄欖綠", "olive clothing palette"),
    ("palette_teal", "青綠色", "teal clothing palette"),
    ("palette_cyan", "青色", "cyan clothing palette"),
    ("palette_blue", "藍色", "blue clothing palette"),
    ("palette_navy", "海軍藍", "navy clothing palette"),
    ("palette_purple", "紫色", "purple clothing palette"),
    ("palette_brown", "棕色", "brown clothing palette"),
    ("palette_beige", "米色", "beige clothing palette"),
    ("palette_cream", "奶油白", "cream clothing palette"),
    ("palette_multicolored", "多色", "multicolored clothing palette"),
    ("palette_copper", "銅色", "copper clothing palette"),
    ("palette_bronze", "青銅色", "bronze clothing palette"),
    ("palette_rose_gold", "玫瑰金", "rose-gold clothing palette"),
)


OUTFIT_PALETTE_ADULT: Final[tuple[ClothingTagDefinition, ...]] = ()
